# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: biorbd-viz
channels:
  - conda-forge
dependencies:
  - python
  - pyomeca
  - vtk
  - pyqt
  - pandas
  - eigen
  - rbdl
  - biorbd
  - packaging
