# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: pyoviz
channels:
  - conda-forge
  - defaults
  - pyomeca
dependencies:
  - python
  - biorbd
  - numpy
  - pyomeca
  - vtk
  - pyqt
